blank_issues_enabled: false
contact_links:
  - name: John Wink
    url: https://signal.me/#eu/-j6vwMmiDaOrWLPPim3so2idZTHM0v1FtoqgBSeY_kgSK8k5VTREjoD69E8ummkJ
    about: 'NUR FÜR NOTFÄLLE! Sollte das System bspw. gar nicht mehr aufrufbar sein'